-- =====================================================
-- Seed Actual Products (37 Products)
-- Run this in your Supabase SQL Editor to seed the database.
-- =====================================================

-- 1. Clear existing products, categories, and brands
DELETE FROM products;
DELETE FROM categories;
DELETE FROM brands;

-- 2. Insert categories
INSERT INTO categories (id, name, slug, description, image, href) VALUES
('protein',       'PROTÉINE',             'protein',       'Protéines de haute qualité pour la récupération et la croissance musculaire', '', '#productsSection'),
('creatine',      'CRÉATINE',             'creatine',      'Boostez votre force et vos performances explosives', '', '#productsSection'),
('sarms',         'SARMS',                'sarms',         'Modulateurs sélectifs des récepteurs aux androgènes pour l''anabolisme ciblé', '', '#productsSection'),
('peptide',       'PEPTIDES',             'peptide',       'Peptides de qualité supérieure pour la vitalité, le soin et la réparation', '', '#productsSection'),
('fat-burner',    'BRÛLEUR DE GRAISSE',   'fat-burner',    'Brûleurs de graisse thermogéniques puissants pour la sèche', '', '#productsSection'),
('preworkout',    'PRÉ-WORKOUT',          'preworkout',    'Énergie maximale et congestion avant l''entraînement', '', '#productsSection'),
('multivitamins', 'MULTIVITAMINES',       'multivitamins', 'Vitamines et minéraux essentiels pour la santé globale', '', '#productsSection'),
('bcaa',          'BCAA & ACIDES AMINÉS', 'bcaa',          'Acides aminés essentiels pour la récupération et la performance', '', '#productsSection');


-- 3. Insert brands
INSERT INTO brands (name, logo, href) VALUES
('Nutrex Research', '', '#'),
('Applied Nutrition', '', '#'),
('Scitec Nutrition', '', '#'),
('OstroVit', '', '#'),
('BioTechUSA', '', '#'),
('TREC', '', '#'),
('Optimum Nutrition', '', '#'),
('Life Pro Nutrition', '', '#'),
('GOLDENBODY', '', '#'),
('Exploramus Invenimus', '', '#'),
('Mutant', '', '#'),
('Myvitamins', '', '#'),
('USN', '', '#'),
('Prozis', '', '#'),
('MyProtein', '', '#');

-- 4. Insert products
INSERT INTO products (id, name, brand, category, tags, description, flavors, sizes, price, old_price, currency, in_stock, badge, featured, show_in_catalog, show_in_new, image, image_hover, href) VALUES
('lipo6-hers', 'LIPO6 HERS ULTRA CONCENTRATE', 'Nutrex Research', 'fat-burner', '{"Brûleur", "Femme", "Minceur"}', 'Lipo6 within an all - there''s a flame waiting to be kinders'' to pooth of passion and heat that ignites our purpose and sent us on a path towards greatness in life... and beyond.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"60 Liqui-Caps"}', 6500, 7500, 'DA', true, 'NOUVEAU', true, true, false, '/images/products/lipo6-hers.png', '/images/products/lipo6-hers.png', '#'),
('shilajit', 'SHILAJIT HIMALAYAN HEALTH', 'Applied Nutrition', 'peptide', '{"Santé", "Vitalité", "Minéraux"}', 'Shilajit de l''Himalaya pur, dosé à 30 000mg. Source naturelle riche en plus de 85 oligo-éléments et acide fulvique pour une vitalité optimale.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"90 Capsules"}', 7800, 8800, 'DA', true, 'PREMIUM', false, true, false, '/images/products/shilajit.png', '/images/products/shilajit.png', '#'),
('jumbo-hardcore', 'JUMBO HARDCORE', 'Scitec Nutrition', 'protein', '{"Gainer", "Masse", "Force"}', 'Formule gainer de masse hardcore contenant 7 sources de glucides et un complexe protéiné multi-sources, sans lactose ni gluten. Idéal pour les hardgainers.', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"5.35kg"}', 14500, 16000, 'DA', true, 'BEST-SELLER', true, true, false, '/images/products/jumbo-hardcore.png', '/images/products/jumbo-hardcore.png', '#'),
('tongkat-ali', 'TONGKAT ALI MALE PERFORMANCE', 'Applied Nutrition', 'sarms', '{"Performance", "Force", "Testo"}', 'Tongkat Ali de dosage maximal 1000mg avec AstraGin. Soutient la performance masculine, la libido, la force et le développement musculaire.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"60 Capsules"}', 8200, 9500, 'DA', true, 'POPULAIRE', true, true, false, '/images/products/tongkat-ali.png', '/images/products/tongkat-ali.png', '#'),
('ostrovit-creatine-watermelon', 'CREATINE MONOHYDRATE (Pastèque)', 'OstroVit', 'creatine', '{"Créatine", "Force", "Pastèque"}', 'Créatine monohydrate micronisée pure 200 Mesh au goût rafraîchissant de pastèque. Sans colorants ni sucres ajoutés.', '[{"name": "Pastèque", "color": "#f49da6"}]', '{"300g"}', 4200, 4900, 'DA', true, 'PROMO', false, true, false, '/images/products/ostrovit-creatine-watermelon.png', '/images/products/ostrovit-creatine-watermelon.png', '#'),
('iso-whey-zero-black-strawberry', 'ISO WHEY ZERO BLACK (Fraise)', 'BioTechUSA', 'protein', '{"Whey", "Isolat", "Fraise"}', 'Isolat de protéines de lactosérum de qualité anabolique avec 3g de créatine par portion, sans sucre ni gluten.', '[{"name": "Fraise", "color": "#e8a0a0"}]', '{"2.27kg"}', 12800, 14500, 'DA', true, 'BEST-SELLER', true, true, false, '/images/products/iso-whey-zero-black-strawberry.png', '/images/products/iso-whey-zero-black-strawberry.png', '#'),
('lipo6-hardcore', 'LIPO6 HARDCORE MAXIMUM STRENGTH', 'Nutrex Research', 'fat-burner', '{"Brûleur", "Thermosect", "Énergie"}', 'The path to greatness is often paved with sacrifice - which is why an many choose not to travel it. Brûleur de graisse thermogénique de force maximale.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"60 Capsules"}', 6800, 7800, 'DA', true, 'EXTRÊME', false, true, false, '/images/products/lipo6-hardcore.png', '/images/products/lipo6-hardcore.png', '#'),
('solid-mass', 'SOLID MASS PROTEIN DRINK', 'TREC', 'protein', '{"Gainer", "Masse", "Glucides"}', 'Solid Mass est un gainer de masse à base de concentré de protéines de lactosérum et de glucides, enrichi en L-Glutamine.', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"10kg"}', 19500, 22000, 'DA', true, 'NOUVEAU', false, true, true, '/images/products/solid-mass.png', '/images/products/solid-mass.png', '#'),
('critical-mass-banana', 'CRITICAL MASS ORIGINAL (Banane)', 'Applied Nutrition', 'protein', '{"Gainer", "Banane", "Calories"}', 'Critical Mass Original Formula est un gainer de masse hyper-calorique premium. Fournit 55g de protéines et 916 kcal par portion.', '[{"name": "Banane", "color": "#d6c04a"}]', '{"6kg"}', 15500, 17500, 'DA', true, 'GÉANT', true, true, false, '/images/products/critical-mass-banana.png', '/images/products/critical-mass-banana.png', '#'),
('extreme-fat-burner', 'EXTREME FAT BURNER', 'Exploramus Invenimus', 'fat-burner', '{"Brûleur", "Carnitine", "Thé Vert"}', 'Brûleur de graisse extrême formulé avec 1200mg de L-Tyrosine, 1000mg de L-Carnitine et 300mg d''extrait de Thé Vert. Goût pastèque.', '[{"name": "Pastèque", "color": "#f49da6"}]', '{"300g"}', 5900, 6800, 'DA', true, 'INTENSE', false, true, false, '/images/products/extreme-fat-burner.png', '/images/products/extreme-fat-burner.png', '#'),
('opti-men', 'OPTI-MEN ACTIVE MULTIVITAMIN', 'Optimum Nutrition', 'multivitamins', '{"Vitamines", "Santé", "Homme"}', 'Complément multivitaminé haut de gamme pour hommes actifs. Contient 36 ingrédients actifs pour soutenir le métabolisme et réduire la fatigue.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"90 Tablettes"}', 5500, 6200, 'DA', true, 'ESSENTIEL', true, true, false, '/images/products/opti-men.png', '/images/products/opti-men.png', '#'),
('life-pro-elektro', 'ELEKTRO INTENSE PRE-WORKOUT', 'Life Pro Nutrition', 'preworkout', '{"Pre-Workout", "Énergie", "Cola"}', 'Pré-workout ultra-concentré avec 3g de Bêta-Alanine, 1.5g de Taurine et 200mg de Caféine anhydre. Formule instantanée.', '[{"name": "Bubble Cola", "color": "#4a2c11"}]', '{"400g"}', 7200, 8200, 'DA', true, 'BOOST', false, true, false, '/images/products/life-pro-elektro.png', '/images/products/life-pro-elektro.png', '#'),
('citrulline-malate', 'CITRULLINE MALATE (Citron Vert)', 'BioTechUSA', 'preworkout', '{"Citrulline", "Pump", "Performance"}', 'L-Citrulline Malate pure sans sucre ni gluten. Optimise la congestion musculaire, la circulation et la force.', '[{"name": "Citron Vert", "color": "#b8d85a"}]', '{"300g"}', 5200, 5900, 'DA', true, 'PUMP', false, true, false, '/images/products/citrulline-malate.png', '/images/products/citrulline-malate.png', '#'),
('marine-collagen-mango', 'MARINE COLLAGEN (Mangue)', 'GOLDENBODY', 'peptide', '{"Collagène", "Soin", "Articulations"}', 'Collagène marin hydrolysé de qualité supérieure pour le soin de la peau, des os et des articulations. Goût Mangue.', '[{"name": "Mangue", "color": "#f4ab21"}]', '{"250g"}', 6800, 7800, 'DA', true, 'PEPTIDES', true, true, false, '/images/products/marine-collagen-mango.png', '/images/products/marine-collagen-mango.png', '#'),
('eaa-glutamine-mango', 'EAA + GLUTAMINE (Mangue)', 'Scitec Nutrition', 'bcaa', '{"EAA", "Acides Aminés", "Récupération"}', 'Combinaison d''acides aminés essentiels (EAA) et de L-Glutamine avec 4000mg de BCAA par portion. Sans sucres ajoutés.', '[{"name": "Mangue", "color": "#f4ab21"}]', '{"300g"}', 6400, 7200, 'DA', true, 'RECUP', false, true, false, '/images/products/eaa-glutamine-mango.png', '/images/products/eaa-glutamine-mango.png', '#'),
('muscle-pro', 'MUSCLE PRO PROTEIN', 'Scitec Nutrition', 'protein', '{"Whey", "Créatine", "Muscle"}', 'Préparation protéinée de haute qualité enrichie en créatine et acides aminés pour stimuler le gain de force et de volume.', '[{"name": "Fraise", "color": "#e8a0a0"}]', '{"2.5kg"}', 11500, 13000, 'DA', true, 'COMPLET', false, true, false, '/images/products/muscle-pro.png', '/images/products/muscle-pro.png', '#'),
('pure-whey-chocolate', 'PURE WHEY (Chocolat)', 'GOLDENBODY', 'protein', '{"Whey", "Chocolat", "WPC"}', 'Complexe multi-protéines haut de gamme (WPC, WPI, WPH) enrichi en enzymes digestives pour une assimilation parfaite. Goût chocolat.', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"1kg"}', 7500, 8500, 'DA', true, 'PROMO', true, true, false, '/images/products/pure-whey-chocolate.png', '/images/products/pure-whey-chocolate.png', '#'),
('body-fuel-preworkout', 'BODY FUEL PRE-WORKOUT', 'Applied Nutrition', 'preworkout', '{"Pre-Workout", "Énergie", "Performance"}', 'Body Fuel Pre-Workout offre une performance optimisée avec un boost d''énergie et de focus intense. Formule explosive.', '[{"name": "Tropical", "color": "#f6c866"}]', '{"300g"}', 6900, 7800, 'DA', true, 'NOUVEAU', false, true, true, '/images/products/body-fuel-preworkout.png', '/images/products/body-fuel-preworkout.png', '#'),
('iso-whey-zero-black-mango', 'ISO WHEY ZERO BLACK (Mangue)', 'BioTechUSA', 'protein', '{"Whey", "Isolat", "Mangue"}', 'Isolat de lactosérum sans créatine, sans sucre ni gluten. Formulé pour soutenir le maintien et le développement de la masse musculaire sèche.', '[{"name": "Mangue", "color": "#f4ab21"}]', '{"900g"}', 5800, 6500, 'DA', true, 'LÉGER', false, true, false, '/images/products/iso-whey-zero-black-mango.png', '/images/products/iso-whey-zero-black-mango.png', '#'),
('yohimbine-liquid', 'YOHIMBINE LIQUIDE', 'Exploramus Invenimus', 'sarms', '{"Sarms", "Sèche", "Graisses"}', 'Yohimbine liquide stérile de qualité pharmaceutique dosée à 750mg. Idéal pour cibler et éliminer les tissus adipeux les plus tenaces.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"180ml"}', 4800, 5500, 'DA', true, 'SÈCHE', true, true, false, '/images/products/yohimbine-liquid.png', '/images/products/yohimbine-liquid.png', '#'),
('lipo6-stim-free', 'LIPO6 STIM-FREE FAT LOSS', 'Nutrex Research', 'fat-burner', '{"Brûleur", "Sans Caféine", "Sain"}', 'Every step you take on your journey is an opportunity. The road isn''t always smooth - but it is through these challenges that we build a lasting legacy. Formule de perte de poids sans stimulants.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"60 Capsules"}', 6200, 7200, 'DA', true, 'SANS-STIM', false, true, false, '/images/products/lipo6-stim-free.png', '/images/products/lipo6-stim-free.png', '#'),
('applied-creatine-500g', 'CREATINE MONOHYDRATE MICRONIZED', 'Applied Nutrition', 'creatine', '{"Créatine", "Micronisée", "Force"}', 'Poudre de créatine monohydrate micronisée pure à 100% avec le logo Informed Sport. Améliore la force et la puissance athlétique.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"500g"}', 6500, 7500, 'DA', true, 'QUALITÉ', true, true, false, '/images/products/applied-creatine-500g.png', '/images/products/applied-creatine-500g.png', '#'),
('trec-casein-protein', 'CASEIN PROTEIN (Chocolat)', 'TREC', 'protein', '{"Caséine", "Nuit", "Récupération"}', 'Protéine de caséine micellaire de qualité supérieure pour une libération prolongée d''acides aminés pendant le sommeil. Goût Chocolat.', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"1kg"}', 8500, 9800, 'DA', true, 'NUIT', false, true, false, '/images/products/trec-casein-protein.png', '/images/products/trec-casein-protein.png', '#'),
('radical-whey', 'RADICAL WHEY', 'Scitec Nutrition', 'protein', '{"Whey", "Cookies", "Isolat"}', 'Combinaison optimale de concentré et d''isolat de whey protéine de qualité avec acides aminés ajoutés. Sans gluten ni huile de palme.', '[{"name": "Cookies & Cream", "color": "#d0c0b2"}]', '{"2.27kg"}', 11900, 13500, 'DA', true, 'NOUVEAU', false, true, true, '/images/products/radical-whey.png', '/images/products/radical-whey.png', '#'),
('ostrovit-creatine-white', 'CREATINE MONOHYDRATE (Blanc)', 'OstroVit', 'creatine', '{"Créatine", "Creapure", "Force"}', 'Créatine monohydrate de très haute pureté optimisée avec Creapure pour des gains de force et de volume maximum.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"250g"}', 3800, 4500, 'DA', true, 'CREAPURE', false, true, false, '/images/products/ostrovit-creatine-white.png', '/images/products/ostrovit-creatine-white.png', '#'),
('hydro-whey-zero', 'HYDRO WHEY ZERO', 'BioTechUSA', 'protein', '{"Whey", "Hydrolysat", "Isolat"}', 'Combinaison ultime d''hydrolysat et d''isolat de lactosérum à digestion ultra-rapide. Sans sucre, sans gluten et sans matières grasses.', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"1.81kg"}', 13500, 15000, 'DA', true, 'HYDRO', true, true, false, '/images/products/hydro-whey-zero.png', '/images/products/hydro-whey-zero.png', '#'),
('iso-whey-platinum', 'ISO WHEY PLATINUM', 'BioTechUSA', 'protein', '{"Whey", "Créatine", "Platinum"}', 'Mélange de whey protéine platinum enrichi en créatine et en L-Glutamine pour maximiser l''anabolisme musculaire.', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"900g"}', 7200, 8200, 'DA', true, 'PLATINUM', false, true, false, '/images/products/iso-whey-platinum.png', '/images/products/iso-whey-platinum.png', '#'),
('scitec-100-whey-professional', '100% WHEY PROTEIN PROFESSIONAL', 'Scitec Nutrition', 'protein', '{"Whey", "Pistache", "WPC"}', 'Boisson protéinée premium à base de concentré et d''isolat de whey protéine avec acides aminés ajoutés. Sans gluten.', '[{"name": "Pistache Chocolat Blanc", "color": "#b2d3a8"}]', '{"2.35kg"}', 12500, 14000, 'DA', true, 'EXCLUSIF', true, true, false, '/images/products/scitec-100-whey-professional.png', '/images/products/scitec-100-whey-professional.png', '#'),
('mega-creatine', 'MEGA CREATINE (Creapure)', 'BioTechUSA', 'creatine', '{"Créatine", "Mega", "Creapure"}', 'Créatine monohydrate de qualité Creapure dosée à 3400mg par jour pour augmenter la puissance musculaire lors d''efforts courts.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"306g"}', 4900, 5500, 'DA', true, 'CREAPURE', false, true, false, '/images/products/mega-creatine.png', '/images/products/mega-creatine.png', '#'),
('life-pro-creatine', 'CREATINE MONOHYDRATE Creapure', 'Life Pro Nutrition', 'creatine', '{"Créatine", "Creapure", "Pure"}', 'Créatine 100% Creapure sans additifs, offrant une solubilité et une biodisponibilité optimales pour booster vos performances physiques.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"250g"}', 4500, 5200, 'DA', true, 'CREAPURE', false, true, false, '/images/products/life-pro-creatine.png', '/images/products/life-pro-creatine.png', '#'),
('mutant-mass', 'MUTANT MASS ORIGINAL', 'Mutant', 'protein', '{"Gainer", "Masse", "Calories"}', 'Mutant Mass est le gainer de poids numéro 1 pour la construction musculaire. Riche en protéines de qualité et nutriments denses.', '[{"name": "Fraise Banane", "color": "#ffd7d0"}]', '{"6.8kg"}', 14900, 16500, 'DA', true, 'POIDS-LOURD', true, true, false, '/images/products/mutant-mass.png', '/images/products/mutant-mass.png', '#'),
('essential-omega3', 'ESSENTIAL OMEGA-3', 'Myvitamins', 'multivitamins', '{"Omega-3", "Santé", "Capsules"}', 'Acides gras essentiels oméga-3 EPA et DHA de première qualité pour soutenir la santé du cœur et des fonctions cérébrales.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"90 Softgels"}', 3500, 4200, 'DA', true, 'SANTÉ', false, true, false, '/images/products/essential-omega3.png', '/images/products/essential-omega3.png', '#'),
('usn-creapure-creatine', 'USN CREAPURE CREATINE', 'USN', 'creatine', '{"Créatine", "Creapure", "Force"}', 'Créatine monohydrate 100% Creapure de marque USN. Conçue pour optimiser la force musculaire explosive et l''endurance.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"170g"}', 4200, 4900, 'DA', true, 'CONGESTION', false, true, false, '/images/products/usn-creapure-creatine.png', '/images/products/usn-creapure-creatine.png', '#'),
('iso-whey-zero-salted-caramel', 'ISO WHEY ZERO (Caramel Salé)', 'BioTechUSA', 'protein', '{"Whey", "Isolat", "Caramel"}', 'Isolat de protéines de lactosérum de qualité premium avec BCAA et L-Glutamine, goût exquis de caramel salé.', '[{"name": "Caramel Salé", "color": "#d6a45c"}]', '{"2.27kg"}', 12500, 14000, 'DA', true, 'DELICIEUX', false, true, false, '/images/products/iso-whey-zero-salted-caramel.png', '/images/products/iso-whey-zero-salted-caramel.png', '#'),
('prozis-marine-collagen', 'PEPTAN MARINE COLLAGEN (Fruit des Bois)', 'Prozis', 'peptide', '{"Collagène", "Soin", "Peau"}', 'Peptides de collagène marin hydrolysés de marque Peptan enrichis en magnésium et vitamine C. Goût fruit des bois.', '[{"name": "Fruit des bois", "color": "#7d3d7b"}]', '{"200g"}', 5200, 5900, 'DA', true, 'PEPTIDES', true, true, false, '/images/products/prozis-marine-collagen.png', '/images/products/prozis-marine-collagen.png', '#'),
('myprotein-impact-whey', 'IMPACT WHEY PROTEIN', 'MyProtein', 'protein', '{"Whey", "Protéine", "Muscle"}', 'Impact Whey Protein de Myprotein fournit 22g de protéines et 5g de BCAA par portion pour soutenir un mode de vie actif et le développement musculaire.', '[{"name": "Cookies & Cream", "color": "#d0c0b2"}]', '{"1kg"}', 7900, 8800, 'DA', true, 'POPULAIRE', false, true, false, '/images/products/myprotein-impact-whey.png', '/images/products/myprotein-impact-whey.png', '#'),
('life-pro-titan', 'TITAN GAINER', 'Life Pro Nutrition', 'protein', '{"Gainer", "Masse", "Titan"}', 'Gainer de masse puissant Titan avec 100% de whey protéine. Sans aspartame, formulé pour un développement musculaire optimal.', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"3kg"}', 13900, 15500, 'DA', true, 'MASSIVE', true, true, false, '/images/products/life-pro-titan.png', '/images/products/life-pro-titan.png', '#');

-- 5. Insert additional brands (batch 2)
INSERT INTO brands (name, logo, href) VALUES
('Naughty Boy', '', '#'),
('Animal', '', '#'),
('Doctor Nutrition', '', '#'),
('Weider', '', '#')
ON CONFLICT (name) DO NOTHING;

-- 6. Insert additional products (batch 2 - 26 products)
INSERT INTO products (id, name, brand, category, tags, description, flavors, sizes, price, old_price, currency, in_stock, badge, featured, show_in_catalog, show_in_new, image, image_hover, href) VALUES
('ostrovit-marine-collagen', 'MARINE COLLAGEN (Cassis)', 'OstroVit', 'peptide', '{"Collagène", "Marin", "Peau"}', 'Collagène marin de type I OstroVit NUTRICOSMETICS à la saveur cassis. 200g de collagène pur pour la santé de la peau, des articulations et des cheveux.', '[{"name": "Black Currant", "color": "#4a1d6e"}]', '{"200g"}', 4900, 5500, 'DA', true, 'NOUVEAU', false, true, false, '/images/products/ostrovit-marine-collagen.png', '/images/products/ostrovit-marine-collagen.png', '#'),
('lipo6-hardcore', 'LIPO-6 HARDCORE', 'Nutrex Research', 'fat-burner', '{"Brûleur", "Hardcore", "Fat Burner"}', 'LIPO-6 HARDCORE de Nutrex Research, le brûleur de graisse maximum avec 60 capsules. Formule avancée pour une perte de poids rapide et efficace.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"60 Capsules"}', 3900, 4500, 'DA', true, 'HARDCORE', false, true, false, '/images/products/lipo6-hardcore.png', '/images/products/lipo6-hardcore.png', '#'),
('scitec-jumbo-green', 'JUMBO (Fraise)', 'Scitec Nutrition', 'protein', '{"Gainer", "Masse", "Protéine"}', 'JUMBO Scitec Nutrition, boisson protéinée en poudre avec 7 glucides, matrix musculaire, complexe énergétique et acides aminés. 6600g pour 30 servings.', '[{"name": "Fraise", "color": "#e8a0a0"}]', '{"6600g"}', 14900, 16500, 'DA', true, 'POPULAIRE', true, true, false, '/images/products/scitec-jumbo-green.png', '/images/products/scitec-jumbo-green.png', '#'),
('biotech-l-carnitine-liquid', 'L-CARNITINE 100.000 LIQUID (Cerise)', 'BioTechUSA', 'fat-burner', '{"L-Carnitine", "Liquide", "Brûleur"}', 'BioTechUSA L-CARNITINE 100.000 LIQUID à la cerise. 2000mg de L-Carnitine par serving avec extrait de thé vert et vitamines. Sans sucre, 500ml (50 servings).', '[{"name": "Cerise", "color": "#c0392b"}]', '{"500ml"}', 3200, 3800, 'DA', true, null, false, true, false, '/images/products/biotech-l-carnitine-liquid.png', '/images/products/biotech-l-carnitine-liquid.png', '#'),
('biotech-creatine-monohydrate', '100% CREATINE MONOHYDRATE', 'BioTechUSA', 'creatine', '{"Créatine", "Monohydrate", "Micronisé"}', 'BioTechUSA 100% CREATINE MONOHYDRATE pure et micronisée, sans arôme. 3g de créatine par jour, sans sucre, sans gluten. 300g (88 servings).', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"300g"}', 2800, 3200, 'DA', true, null, false, true, false, '/images/products/biotech-creatine-monohydrate.png', '/images/products/biotech-creatine-monohydrate.png', '#'),
('biotech-iso-whey-zero-black-strawberry', 'ISO WHEY ZERO BLACK (Fraise)', 'BioTechUSA', 'protein', '{"Isolat", "Whey", "Fraise"}', 'BioTechUSA ISO WHEY ZERO BLACK Fraise — isolat de whey anabolisant à 80% de protéines. Sans lactose, sans sucre, sans gluten, sans huile de palme. Avec 3g de créatine. 2270g (75 servings).', '[{"name": "Fraise", "color": "#e8a0a0"}]', '{"2270g"}', 12500, 14000, 'DA', true, 'BEST SELLER', true, true, false, '/images/products/biotech-iso-whey-zero-black-strawberry.png', '/images/products/biotech-iso-whey-zero-black-strawberry.png', '#'),
('usn-isopro-whey', 'ISOPRO WHEY (Vanille)', 'USN', 'protein', '{"Isolat", "Whey", "Vanille"}', 'USN GOLDENBODY ISOPRO WHEY 100% isolat de whey protéine. Leader en nutrition sportive, parfum vanille pour une récupération musculaire optimale.', '[{"name": "Vanille", "color": "#f5e6c8"}]', '{"1kg"}', 8900, 9900, 'DA', true, null, false, true, false, '/images/products/usn-isopro-whey.png', '/images/products/usn-isopro-whey.png', '#'),
('lipo6-nighttime', 'LIPO6 NIGHTTIME', 'Nutrex Research', 'fat-burner', '{"Nuit", "Sommeil", "Brûleur"}', 'LIPO6 NIGHTTIME — perte de poids nocturne et support du sommeil. Dans le royaume des rêves, nous trouvons l''inspiration et le rajeunissement. 30 capsules, une seule pilule.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"30 Capsules"}', 4200, 4800, 'DA', true, 'NUIT', false, true, false, '/images/products/lipo6-nighttime.png', '/images/products/lipo6-nighttime.png', '#'),
('applied-critical-whey', 'CRITICAL WHEY (Fraise)', 'Applied Nutrition', 'protein', '{"Whey", "Protéine", "Fraise"}', 'Applied Nutrition CRITICAL WHEY Advanced Protein certifié Informed Sport. 21g de protéines, 110 calories par serving. 67 servings, parfum Strawberry Milkshake.', '[{"name": "Strawberry Milkshake", "color": "#f4b8c8"}]', '{"2kg"}', 7500, 8500, 'DA', true, 'CERTIFIÉ', false, true, false, '/images/products/applied-critical-whey.png', '/images/products/applied-critical-whey.png', '#'),
('lipo6-black', 'LIPO6 BLACK ULTRA CONCENTRATE', 'Nutrex Research', 'fat-burner', '{"Brûleur", "Ultra", "Concentrate"}', 'LIPO6 BLACK Ultra Concentrate de Nutrex Research. Formule ultra-concentrée avec Vitamine C, Capsule B et Cynomite. 60 LIQUI-CAPS, complément alimentaire.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"60 Liqui-Caps"}', 3900, 4500, 'DA', true, 'ULTRA', false, true, false, '/images/products/lipo6-black.png', '/images/products/lipo6-black.png', '#'),
('naughty-boy-whey', 'WHEY (Vanille Glacée)', 'Naughty Boy', 'protein', '{"Whey", "Protéine", "Vanille"}', 'Naughty Boy WHEY Advanced Protein — 100g de protéines, 1.6g de lipides. Parfum Vanilla Ice Cream pour une récupération musculaire de haute qualité.', '[{"name": "Vanilla Ice Cream", "color": "#f5e6c8"}]', '{"1kg"}', 7500, 8500, 'DA', true, null, false, true, false, '/images/products/naughty-boy-whey.png', '/images/products/naughty-boy-whey.png', '#'),
('animal-pak', 'PAK (Multivitamine)', 'Animal', 'multivitamins', '{"Multivitamine", "Pack", "Performance"}', 'Animal PAK Ultimate Foundation — 20-en-1 multivitamine pack améliorée avec 25% moins de pilules. Vitamines, minéraux, antioxydants, ginseng sibérien, curcuma, chardon-marie, enzymes digestives. 44 packs.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"44 Packets"}', 5500, 6200, 'DA', true, 'PREMIUM', true, true, false, '/images/products/animal-pak.png', '/images/products/animal-pak.png', '#'),
('myvitamins-multivitamin-gummies', 'MULTIVITAMIN GUMMIES (Vimto)', 'Myvitamins', 'multivitamins', '{"Gummies", "Multivitamine", "Vimto"}', 'Myvitamins MULTIVITAMIN GUMMIES parfum Vimto. Multivitamines délicieuses sous forme de gummies. 60 gummies par boîte, formulées pour les adultes actifs.', '[{"name": "Vimto", "color": "#6d1d8f"}]', '{"60 Gummies"}', 3200, 3800, 'DA', true, null, false, true, false, '/images/products/myvitamins-multivitamin-gummies.png', '/images/products/myvitamins-multivitamin-gummies.png', '#'),
('myprotein-impact-creatine-1kg', 'IMPACT CREATINE (1kg)', 'MyProtein', 'creatine', '{"Créatine", "Performance", "Monohydrate"}', 'MyProtein IMPACT Creatine — augmente les performances physiques et supporte l''exercice à haute intensité. Non aromatisé, 1kg ≈ 333 servings.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"1kg"}', 6500, 7500, 'DA', true, 'BEST VALUE', true, true, false, '/images/products/myprotein-impact-creatine-1kg.png', '/images/products/myprotein-impact-creatine-1kg.png', '#'),
('on-platinum-hydro-whey', 'PLATINUM HYDRO WHEY (Chocolat)', 'Optimum Nutrition', 'protein', '{"Hydrolysat", "Isolat", "Whey"}', 'Optimum Nutrition PLATINUM HYDRO WHEY au chocolat. Isolat de whey hydrolysé avancé — 30g de protéines, 9.5g de BCAAs par serving. 100% de la protéine issue d''hydrolysat et d''isolat. 1.6kg.', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"1.6kg"}', 14500, 16500, 'DA', true, 'PLATINUM', true, true, false, '/images/products/on-platinum-hydro-whey.png', '/images/products/on-platinum-hydro-whey.png', '#'),
('applied-multivitamin-complex', 'MULTI-VITAMIN COMPLEX', 'Applied Nutrition', 'multivitamins', '{"Multivitamine", "Complexe", "Capsules"}', 'Applied Nutrition MULTI-VITAMIN COMPLEX — complément vitaminique complet en capsules claires. Soutien des vitamines et micronutriments essentiels.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"20 Capsules"}', 2500, 2900, 'DA', true, null, false, true, false, '/images/products/applied-multivitamin-complex.png', '/images/products/applied-multivitamin-complex.png', '#'),
('on-opti-women', 'OPTI-WOMEN', 'Optimum Nutrition', 'multivitamins', '{"Femme", "Multivitamine", "Santé"}', 'Optimum Nutrition OPTI-WOMEN multivitamine pour femmes actives. 23 ingrédients actifs, soutient la fonction métabolique et immunitaire, réduit la fatigue. 60 capsules.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"60 Capsules"}', 5200, 5900, 'DA', true, 'FEMME', false, true, false, '/images/products/on-opti-women.png', '/images/products/on-opti-women.png', '#'),
('applied-beef-mass-gainer', 'BEEF MASS GAINER', 'Applied Nutrition', 'protein', '{"Gainer", "Bœuf", "Masse"}', 'Applied Nutrition BEEF MASS GAINER — force, muscle, masse. 42g de protéines, 70g de glucides doubles, 454 kcal. Faible en sucre, sans lactose, sans produits laitiers.', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"3kg"}', 8900, 10000, 'DA', true, 'LACTOSE FREE', false, true, false, '/images/products/applied-beef-mass-gainer.png', '/images/products/applied-beef-mass-gainer.png', '#'),
('myprotein-impact-creatine-small', 'IMPACT CREATINE (250g)', 'MyProtein', 'creatine', '{"Créatine", "Performance", "Monohydrate"}', 'MyProtein IMPACT Creatine — 3g de créatine par serving. Augmente les performances physiques et supporte l''exercice à haute intensité. Format pratique.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"250g"}', 1900, 2400, 'DA', true, null, false, true, false, '/images/products/myprotein-impact-creatine-small.png', '/images/products/myprotein-impact-creatine-small.png', '#'),
('extreme-fat-burner-pink', 'EXTREME FAT BURNER (Pastèque)', 'Nutrex Research', 'fat-burner', '{"Brûleur", "Pastèque", "L-Carnitine"}', 'EXTREME FAT BURNER parfum pastèque — 1200mg L-Tyrosine, 1000mg L-Carnitine, 300mg d''extrait de thé vert. Complément alimentaire puissant pour la perte de poids.', '[{"name": "Pastèque", "color": "#f49da6"}]', '{"300g"}', 3200, 3800, 'DA', true, 'EXTREME', false, true, false, '/images/products/extreme-fat-burner-pink.png', '/images/products/extreme-fat-burner-pink.png', '#'),
('doctor-nutrition-amino-eaa', 'AMINO EAA (Cerise)', 'Doctor Nutrition', 'bcaa', '{"Acides Aminés", "EAA", "Cerise"}', 'Doctor Nutrition AMINO EAA — acides aminés essentiels parfum cerise. 30 servings, 300g. La base pour la récupération et le maintien musculaire.', '[{"name": "Cerise", "color": "#c0392b"}]', '{"300g"}', 3900, 4500, 'DA', true, null, false, true, false, '/images/products/doctor-nutrition-amino-eaa.png', '/images/products/doctor-nutrition-amino-eaa.png', '#'),
('weider-mega-mass-4000', 'MEGA MASS 4000 (Chocolat)', 'Weider', 'protein', '{"Gainer", "Masse", "Créatine"}', 'Weider MEGA MASS 4000 nouvelle formule — conçu pour les hardgainers. +800 kcal par serving, 49g de protéines, avec Creapure. Sans aspartame, sucre réduit. 4kg.', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"4kg"}', 9500, 10900, 'DA', true, 'HARDGAINER', true, true, false, '/images/products/weider-mega-mass-4000.png', '/images/products/weider-mega-mass-4000.png', '#'),
('biotech-hyper-mass', 'HYPER MASS (Chocolat)', 'BioTechUSA', 'protein', '{"Gainer", "Masse", "Créatine"}', 'BioTechUSA HYPER MASS — boisson protéinée en poudre avec glucides et créatine. Faible en sucre, haute en protéines. Parfum chocolat, 7004g (104 servings).', '[{"name": "Chocolat", "color": "#3d1c02"}]', '{"7004g"}', 11500, 13000, 'DA', true, 'MEGA', false, true, false, '/images/products/biotech-hyper-mass.png', '/images/products/biotech-hyper-mass.png', '#'),
('biotech-citrulline-malate', 'CITRULLINE MALATE (Citron Vert)', 'BioTechUSA', 'preworkout', '{"Citrulline", "Pump", "Pre-Workout"}', 'BioTechUSA CITRULLINE MALATE parfum citron vert. 1.5g L-Citrulline + 1.5g Malate par serving. Sans sucre, sans gluten. 300g (93 servings) pour un pump maximal.', '[{"name": "Citron Vert", "color": "#b8d85a"}]', '{"300g"}', 2800, 3200, 'DA', true, null, false, true, false, '/images/products/biotech-citrulline-malate.png', '/images/products/biotech-citrulline-malate.png', '#'),
('biotech-iso-whey-zero-pistachio', 'ISO WHEY ZERO (Pistache)', 'BioTechUSA', 'protein', '{"Isolat", "Whey", "Pistache"}', 'BioTechUSA ISO WHEY ZERO Pistache — isolat de whey premium avec L-Glutamine et BCAAs. Protéine native non filtrée, réduite en lactose, sans sucre, sans gluten, sans huile de palme. 2270g (72 servings).', '[{"name": "Pistache", "color": "#b2d3a8"}]', '{"2270g"}', 12500, 14000, 'DA', true, 'PREMIUM', true, true, false, '/images/products/biotech-iso-whey-zero-pistachio.png', '/images/products/biotech-iso-whey-zero-pistachio.png', '#'),
('myprotein-l-glutamine', 'L-GLUTAMINE', 'MyProtein', 'bcaa', '{"Glutamine", "Acides Aminés", "Récupération"}', 'MyProtein L-GLUTAMINE — acide aminé essentiel formulé par des experts, non aromatisé. 5g de L-Glutamine pour la récupération musculaire et le système immunitaire.', '[{"name": "Non aromatisé", "color": "#8f8f8f"}]', '{"500g"}', 3200, 3800, 'DA', true, null, false, true, false, '/images/products/myprotein-l-glutamine.png', '/images/products/myprotein-l-glutamine.png', '#')
ON CONFLICT (id) DO NOTHING;


